### ISSUE TITLE
工程下载下来后，pod install 有问题，希望能处理下

### ISSUE THREAD

**Issue by SongJay** [huzhiqin/U17#1]
![image](https://user-images.githubusercontent.com/9447658/83090071-69f93880-a0ca-11ea-880f-a3bed1661b53.png)

**Comment by huzhiqin** [comment]
@SongJay 试试命令：yum update -y nss curl libcurl 
方案链接：https://www.cnblogs.com/doubilaile/p/8479967.html
如果以上还不行，试着把所有pod相关的都删除（Pods文件夹、Podfile.lock），删除后再重新pod install试试，我这边刚刚试过了，clone下来后直接pod install没问题。

**Comment by SongJay** [comment]
![image](https://user-images.githubusercontent.com/9447658/83710890-662e5e80-a654-11ea-9509-fec7339eb948.png)
我修改了podfile里面的内容就可以了
